### ISSUE TITLE
Feature request: Option to use individual password to protect the app

### ISSUE THREAD

**Issue by MaWo2** [flocke/andOTP#23]
I suggest to include the option to define an individual password/PIN to protect the app. Currently, (v0.2.4 F-Droid) only the phone credentials can be used.

**Comment by grrrrr** [comment]
Agreed the use of the system password negates any benefits.  If the idea is to protect the tokens from an attacker, if they already know the system password they can open andOTP

The GuardianProject's various libraries would be perfect use for this.   SQLCipher and IOCipher would provide secure and password protected storage.   Using PanicKit would allow for destruction of the tokens / container in extreme situations

https://guardianproject.info/code/

**Comment by flocke** [comment]
Just to clarify: the system password is in no way used to encrypt the data of andOTP.
It is only a check before starting the app to add a little protection from someone who just picks up your unlocked phone.

I am not gonna change the way the data is stored, which is in the Android KeyStore.
However I'm gonna add the option to unlock the app with a custom password instead of the device credentials.

If you want your data to be encrypted with a custom password there is already a fork of OTP Authenticator out there which does that (OneTimePad).

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ikocevski** [comment]
6 digit pin would be awesome. Anyway this has to be implemented so as to avoid someone that has your phone to access your OTPs. You can also export these unencrypted which makes it a necessity.

**Comment by flocke** [comment]
Done, in the next release you will be able to set an individual password or PIN to unlock the app.
