### ISSUE TITLE
Encrypt backup using master password

### ISSUE THREAD

**Issue by jerryn70** [flocke/andOTP#4]
Currently we have 2 backup options, plain text JSON backup and encrypted OpenPGP backup.

Plain text is not safe and OpenPGP is safe. 

The problem is not everyone is using OpenPGP and some are not interested in using OpenPGP and the remaining others dont know how to use OpenPGP.

For me i dont know how to use OpenPGP and i dont like to use it.

My idea is to add a master password option to the app and encrypt the backup using that master password (like password manager apps are doing)

This help the people who are not using OpenPGP.

Current issues :

1) Already password/lock option is available.

Solution : For this implimentation we need to remove the current lock method we are using in the app (using the device default lock method ) 

2)  Hard to type password everytime to open app. 

Solution : We can add a PIN option to easily unlock app. (like password managers)

**Comment by flocke** [comment]
I don't mind adding an option to have encrypted backups with a password, but this will need some additional research since this is my first Android app.

But I won't add a master password for opening the app itself, there already is a fork of OTP Authenticator that encrypts the stored internal data with a master password out there: https://github.com/kckrinke/onetimepad

Also the current method of locking the app has nothing to do with the encryption, it's just an additional check that closes the app again if the authentication fails. The encryption of the data is not coupled to the authentication in any way.
